name = "PointSetVisualizer"
uuid = "c1998724-06c8-4b73-8944-aed6cfa5d6a5"
authors = ["Roy Chih Chung Wang <roy.c.c.wang@proton.me>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.13.6"
julia = "1.11"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]